hash-format = "sha256"

[[files]]
file = "mods/BetterWaystonesMenu-1.2.0+mc1.18.2.jar"
hash = "69e53aa3b5d18326895d4c30118e8386ed3057ceeaa592e9a5ce8009d1985185"

[[files]]
file = "mods/additional-lights.pw.toml"
hash = "32534e0155bb0d8eb0683de29bd181f563fd4bbdbad61518e4ffffb097058e44"
metafile = true

[[files]]
file = "mods/advanced-xray.pw.toml"
hash = "6e4d2c5a7d88cf47e069ca597ec3d5dc13b8ca0b8f2cdd96d6dec1e7c1290ee6"
metafile = true

[[files]]
file = "mods/alexs-mobs.pw.toml"
hash = "03da06567af6005bcfd94525e773bb49b448c58b161757f8f5680b857459766c"
metafile = true

[[files]]
file = "mods/apathy-mod.pw.toml"
hash = "47c213e414f87b34662cc173b88296295a96ada778719c66df683fca3e962e96"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "84abec9cda0e905d2e503066a11fd6addb6b28e6604c633485993c25850b7198"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "0112d33ef55ca337e21a5d71bb570ef8a72eb408f68ad1c9b7f58835cf579980"
metafile = true

[[files]]
file = "mods/autofish-for-forge.pw.toml"
hash = "b944133ce63c9cac56be214bb4aea44c01d4d744c366a205faac831e711163b5"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "23c80ede3b259c1c908ace792f0b95d7c6cb2155f2fcc1b3493e569b656162c2"
metafile = true

[[files]]
file = "mods/betterwaystonesmenu.pw.toml"
hash = "82dacd554d80980cdbf37c208eb58a971609a2d8362d24888a77e93c37ecdebf"
metafile = true

[[files]]
file = "mods/bookshelf.pw.toml"
hash = "1d7f95592de63e85db46a17cb90c0386b9810954ae55dea2da7ba6291db0cb4d"
metafile = true

[[files]]
file = "mods/born-in-chaos.pw.toml"
hash = "5db9b68523e0cbc47516e3760479f3ffbc10d0064cf45bcd998f2154c5fcb12f"
metafile = true

[[files]]
file = "mods/camera-mod.pw.toml"
hash = "06fadd1cf6120d4c660bf130cc8e3f4c595d2b8471d2c8d860229df475ff1a18"
metafile = true

[[files]]
file = "mods/canary.pw.toml"
hash = "75e650b0bd889e5f748fe4f637109201282c0a836dc182e82a18f88bb3d2e863"
metafile = true

[[files]]
file = "mods/chipped.pw.toml"
hash = "3882c802ffa760a9c7581bb04bde212173edb903d54a931c5cbdf83eff6053b9"
metafile = true

[[files]]
file = "mods/citadel.pw.toml"
hash = "dbe6a9e42390a6e5fa08ebd31c44567981ec8face7afff290930d542bd87f6e7"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "4f495fc01341d03538efb6bca187cfee04c9ed08d30184dfc3384bf73c1dbb31"
metafile = true

[[files]]
file = "mods/comforts.pw.toml"
hash = "26a174a078be4f8c995515972263d71322aae276d8cd5acb49337e55ff86c06f"
metafile = true

[[files]]
file = "mods/configured.pw.toml"
hash = "d647c96a37237cca3668cff8e0467a411e25eb783a9ce7c7d05a414a98da986c"
metafile = true

[[files]]
file = "mods/connected-glass.pw.toml"
hash = "ac953674161b7a6183b47327011e26ea167b85addcae6e7e90faf54405e705dd"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "e4d2d558f3a44c059788554b6394c126d2993be30c8649da92fabb8fd2e4623f"
metafile = true

[[files]]
file = "mods/cooking-for-blockheads.pw.toml"
hash = "12ca499aff1c91c2e2ec3d094d4b9d6799bc2d2c8445827ed2ca07419f323605"
metafile = true

[[files]]
file = "mods/corpse.pw.toml"
hash = "e4155e11b80301e0dbc76f64deea0f7b73c2e8086782ce8a7cdc5b72b2218172"
metafile = true

[[files]]
file = "mods/cosmetic-armor-reworked.pw.toml"
hash = "1d4cbe411ab2aa943d6f9ab878416b53ff9a683d395fb413f841579c5b470f39"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "f8f420ecca3eeccc8ad458369654f2f73e0a729472d95afd019e819b2a5b73ee"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "00915ac3c3b388ff4225d163b38c2306ab6c7a5b03aa28f2a23e85726d5e2213"
metafile = true

[[files]]
file = "mods/creeper-overhaul.pw.toml"
hash = "938447d1a7b78c6a03b577d2f60a0fcf9ca3a5403304a9bdc201b9dbeacb89be"
metafile = true

[[files]]
file = "mods/croptopia.pw.toml"
hash = "9dd611c04b7f25288d20a62daf0f1abd257cf64d06c51a059f56662209afca77"
metafile = true

[[files]]
file = "mods/ctm.pw.toml"
hash = "aaeab662940679b8ef5074189d480bd04934334bc32d29931538c8bf2d7050cd"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "3fbeebeafd2cf899a3235106343689c2e8522deb8eea32fe1bbdb28563fd57f7"
metafile = true

[[files]]
file = "mods/dynamictrees.pw.toml"
hash = "687763852b583a03f03ab2a235be39428e5a08490f63c7d1186a6aadd1b355c7"
metafile = true

[[files]]
file = "mods/emotecraft-forge.pw.toml"
hash = "4df84c4c3e6ea3b6f75d8b34147843118fc02e8b73a583d6c13e2be242603e78"
metafile = true

[[files]]
file = "mods/enchantment-descriptions.pw.toml"
hash = "9698d77c462cbf16a5c3db9bc3cea684b36f3a26ef9320683f38c9525c678948"
metafile = true

[[files]]
file = "mods/enemy-expansion.pw.toml"
hash = "f4ad62523b661d77de06173f2f1cd32401b7010b01b52d75cc262ba1281916c2"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "0dea56eed4dcc7157302c9f61bc993d1cfabbb5b5ddb30ba0ff25af281c77756"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
hash = "379d6716ffb05e693aac86723e30bd6db53b98fea48d07eddb8238a260ec6d4e"
metafile = true

[[files]]
file = "mods/farsight.pw.toml"
hash = "a23cd083c19f961223880ce56bc9ce8cba6532d60b012700a1ec64a443d36acf"
metafile = true

[[files]]
file = "mods/fast-leaf-decay.pw.toml"
hash = "80e1013e0049365892e0c05b6263062ff5d13a2638d4f97129bb2985dbafa424"
metafile = true

[[files]]
file = "mods/ferritecore.pw.toml"
hash = "a6944c6e912ec3c1293b84cbed86ea1a0dbd8f1827435cb1bf2849d37b42a0dc"
metafile = true

[[files]]
file = "mods/framedblocks.pw.toml"
hash = "4d71a6594696cc46a5530ba85c0314a734473c1003b9aab876be5d7a3ed7dd6b"
metafile = true

[[files]]
file = "mods/free-cam.pw.toml"
hash = "66cecb3526e5e5c3f4c36e2e92e21c9a588523fb7c71b2f4f0f7107c31c7a59e"
metafile = true

[[files]]
file = "mods/gamemenumodoption.pw.toml"
hash = "5fc5e2b2572dcd8073a24cf0a7c5cd089bff12666693e16cd243648f8cce9da3"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "e2ecdb0eaa4c2118a320126f5993f781a302d8dec01a041374d5381ed54d6a44"
metafile = true

[[files]]
file = "mods/immersive-armors.pw.toml"
hash = "7915d41a867de042dea8e4606bac70923ef124f49e7dfc1787f6bf9c9681e533"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
hash = "88a69dec7e83b69c2d314d74d9df5fcde3d92ee1c4233ff2ce203c81550e0681"
metafile = true

[[files]]
file = "mods/iris-flywheel-compat.pw.toml"
hash = "7fd6bc3e0bc4c45ca6ba8beef3c66393f9d3643d51e0dfc3c302703e2b221f46"
metafile = true

[[files]]
file = "mods/isle-of-berk-addons.pw.toml"
hash = "cd52ea5e5e3401f83322fdf9987015efd5ade3330a73724e42c56fa1a53e56c9"
metafile = true

[[files]]
file = "mods/isle-of-berk.pw.toml"
hash = "3fd4f320fe7d7a427faa5e2c38a72b06364eb5f202ff03cdd8383b9bb9c69f17"
metafile = true

[[files]]
file = "mods/item-filters.pw.toml"
hash = "b5d50a2815512a7e2224173edd77f7b798c29607640f8144e4c3f122d61b40d6"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "68b34a638042fcb11810a6266be7c1075cd39e601485f1c30c32569deb13df46"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "79be136bfe56867556786ec4abe2d3d7ad35d8f33070f55c42590820e698fc56"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "5209de0e2eeccacc8f2d554681f92deb78b4c108e596c60e580d5e2a1b3f2756"
metafile = true

[[files]]
file = "mods/just-enough-resources-jer.pw.toml"
hash = "2f86406baf5c931fbb9b37c0ed93c8d041fe32eb6c9b20b915a351e0a1bfb0fc"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "8fd61b13a6da4b7f5cdf69ab6241c296b3019846a1635a2cbb427fbbb21635b2"
metafile = true

[[files]]
file = "mods/libIPN-forge-1.18.2-3.0.2.jar"
hash = "7ca9a14728817e7e612781d0c4985d0da282a6571f30d646d2a2f2de03e5251d"

[[files]]
file = "mods/light-overlay.pw.toml"
hash = "b4b6828ba835038615eb2ee91d8b1eaeef53687952bf89769c680854d7dba63f"
metafile = true

[[files]]
file = "mods/mmmmmmmmmmmm.pw.toml"
hash = "543cae965a82c348b1a64fce5b3d7a4690970b6db6f38518c6f99771cec9a387"
metafile = true

[[files]]
file = "mods/modern-life.pw.toml"
hash = "88db3b5f78e507684a669e2989866def4b443bdc9e3aa936382cc9e1b2829c22"
metafile = true

[[files]]
file = "mods/morevanillaarmor.pw.toml"
hash = "524f7db824b7a9a688578e34bd0cd9a461231fac9462b559c7b35fd9e1110040"
metafile = true

[[files]]
file = "mods/mowzies-mobs.pw.toml"
hash = "5a61f6b9d1c906a03305bcfd9cfac7efe99e99a5bd8fe49984f9a5e8671ebe9f"
metafile = true

[[files]]
file = "mods/mrcrayfish-furniture-mod.pw.toml"
hash = "eab360710dfebe9b6f7f5c260acfc8275663db2245c85a1e436a78d8e7531dd5"
metafile = true

[[files]]
file = "mods/natures-compass.pw.toml"
hash = "e3b607348fc4084c8aece8cccaa3c58af8d12e518c305bdbe044eabc2bb0b472"
metafile = true

[[files]]
file = "mods/nofog.pw.toml"
hash = "8d313dc0061c2283a06d033cd2bda44841b775a3509da99410da420f09e1be2d"
metafile = true

[[files]]
file = "mods/oculus.pw.toml"
hash = "fad0e1c59d0548afbcbe2e34d25fbf97cf4c6effe40b3f7e2b93dd5c546ee601"
metafile = true

[[files]]
file = "mods/oh-the-biomes-youll-go.pw.toml"
hash = "4a5234958a5656afaf5c8cd1c907cbc89a58c6fa0f806e6f8e8b3f98b39dcfe8"
metafile = true

[[files]]
file = "mods/ok-zoomer-forge.pw.toml"
hash = "4d90fc54c60eac4c117e60e98659519c4a1411e85e72b6da8932b6ca7dc94642"
metafile = true

[[files]]
file = "mods/openblocks-elevator.pw.toml"
hash = "9ba7ce600676fa147a460fa3ec04712943ed81c72a24774f2c2b721c113986a3"
metafile = true

[[files]]
file = "mods/orcz.pw.toml"
hash = "556d506a1379456ec670e6a27491ca595c3af5cf34b61dd105ade96deb0eff8d"
metafile = true

[[files]]
file = "mods/paragliders.pw.toml"
hash = "41f827db35d1d0f8321a1ac6669adcf88ea908b60d9f1914e580b4b80c7450df"
metafile = true

[[files]]
file = "mods/playeranimator.pw.toml"
hash = "13178bc94d32f9b96e0fc78b8014eabd0ed3b1a21931f2f6027ff0eebc5e7e33"
metafile = true

[[files]]
file = "mods/playerrevive.pw.toml"
hash = "cc5e1f000907c42c15b85641b5b9135fa8491e12ad3921d8a16cff91e050df97"
metafile = true

[[files]]
file = "mods/pluto.pw.toml"
hash = "d157980f6e4b7a62b870b9a86aafb8f07342800a6ffcffb945567c6b5203af2e"
metafile = true

[[files]]
file = "mods/polymorph.pw.toml"
hash = "75f57aa3190d8ce4552479c17be1a6fe5269ac25755dd87542ad8857401b4ccb"
metafile = true

[[files]]
file = "mods/quick-harvest.pw.toml"
hash = "99a0a1f94e0c99b345c5b754bc4ca4f48b548eb57fe5d677d3a6633d5ebb0b38"
metafile = true

[[files]]
file = "mods/rubidium.pw.toml"
hash = "07820f2e9cf69d227919b049139bb03f83332d3ca2af5b4253c6e88893c47680"
metafile = true

[[files]]
file = "mods/saturn.pw.toml"
hash = "82bb69add7234aa50636277b38aa25eca2f9e6277253a62af1e6c4b3cbc05481"
metafile = true

[[files]]
file = "mods/security-craft.pw.toml"
hash = "eb865277c901002566ec817bb6d2f58b1e0770a24ab7d07518372200a4d06d72"
metafile = true

[[files]]
file = "mods/selene.pw.toml"
hash = "7cfcda9ba0dcba7d302f9ea1694e9a420b8e214b3094093d7ded6c5d4a3a6d92"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "bef1c188b18a6dd4014eff5a926d0fba14b13db9712e42ee87a63059aaf8b389"
metafile = true

[[files]]
file = "mods/smooth-boot-reloaded.pw.toml"
hash = "ae96852dffcc7cf0bcf5c80519c5a53daf52dd8a444f95743fdd4af1d86d976d"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks.pw.toml"
hash = "356f9483aee50732cf162981225ea40a301099b82d570fb1ed6deadc78b16474"
metafile = true

[[files]]
file = "mods/sophisticated-core.pw.toml"
hash = "b851c35124b70292391c9b4dcdeb7205d36c7649e976909d3e1ba5a265c8fb16"
metafile = true

[[files]]
file = "mods/sophisticated-storage.pw.toml"
hash = "e513019907f8249d32e22c2574950e7ecb9bd9b4d87eb48dd08c89eb6e7c7ff6"
metafile = true

[[files]]
file = "mods/starlight-forge.pw.toml"
hash = "cf0274e0db473a80ea8d8442362d3e7e76639018504b9ff37fa61aa6044b8a60"
metafile = true

[[files]]
file = "mods/storage-drawers.pw.toml"
hash = "b5e478bee6fd909d03453c2bdac37211e65d983a92a383ae4cb8975a9e493ad9"
metafile = true

[[files]]
file = "mods/structures-compass.pw.toml"
hash = "085b625eab66b0979668785503343330c3e07573e7f3775ac92c7c75ae1b7b93"
metafile = true

[[files]]
file = "mods/supermartijn642s-core-lib.pw.toml"
hash = "1c300c6bb92a6105eed15fc487309c4511e40d9238a57cae1a0b42154b3d2082"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
hash = "bbcac108eb3d98535842213f234673bb2725e8abed191c8dc5c3893a3675999a"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
hash = "526f1411f2287247b09ebe85ce4ba29daaad56f1a817d163ec194f78b11bb8ef"
metafile = true

[[files]]
file = "mods/toms-storage.pw.toml"
hash = "8efc83f181371fb79f6e3b3510750543ebf9f85bf5282fbb36838b8ee044b8b4"
metafile = true

[[files]]
file = "mods/trashslot.pw.toml"
hash = "b9dacfb1a5e2f9a3372801cf515326e99c9ebd2a25086d2d2d4848a76ced176f"
metafile = true

[[files]]
file = "mods/undead-unleashed.pw.toml"
hash = "5b1976d9c10534b3007af8a2cd80d88f0da8c44a352604d0c735107e13c15f22"
metafile = true

[[files]]
file = "mods/untamedwilds.pw.toml"
hash = "23fcc3bc9ceebaef602d0370664a29f15a896ca5770752bbb042cf24cc0fc259"
metafile = true

[[files]]
file = "mods/waystones.pw.toml"
hash = "7566e584dc2ba7115ce13ee79f5f15f32798f9559d3c01decace774634893159"
metafile = true

[[files]]
file = "mods/when-dungeons-arise.pw.toml"
hash = "01399fef27404a511bfc9b6dad93773e1847c394e86d258d4fa1f3ef9171288c"
metafile = true

[[files]]
file = "packwiz-installer-bootstrap.jar"
hash = "a8fbb24dc604278e97f4688e82d3d91a318b98efc08d5dbfcbcbcab6443d116c"

[[files]]
file = "packwiz-installer.jar"
hash = "3cc3ebd57f1ec54a8ceaccc76e193201f8c957c563c9461253d112c5b087d744"

[[files]]
file = "packwiz.json"
hash = "541ec6a282a389484cc81faee56461f393a09552ddac144e914c3f0e07d7ec53"
